### ISSUE TITLE
Alfodoo V11

### ISSUE THREAD

**Issue by lmignon** [acsone/alfodoo#102]
Currently, Alfodoo is available for Odoo 9 and 10. The modules suite needs to be migrated to the version 11 of Odoo which has been released on October 2017.

We would like to know if the community is interested to have the existing alfodoo modules to be compliant with Odoo 11 both community and enterprise versions and wants to participate in the financing of this technical migration?

Our initial objective was to initiate a crowdfunding project for this migration. We can relaunch a crowdfunding project if enough people are interested.

If you are interested by the migration and want to contribute, send an email to info@acsone.eu

**Comment by lukebranch** [comment]
I'd definitely be interested in this. I have a customer migrating from 10.e > 11.0e soon, and it i'm certain they'd be interested in contributing significantly to a crowdfunding campaign for this.

**Comment by sterbhai** [comment]
We are interested in migration to odoo 11. As a small company we would participate as good as possible. We run odoo CE and Alfresco CE.
We are looking for more flexibility for the location of the connected folders between odoo and alfresco, so the user could select the folder/node to attach to an object in odoo.

**Comment by lukebranch** [comment]
Our customer is now migrated to 11.0, and will be interested in setting up a DMS with Alfodoo in the second phase of their project. I believe in this way we could contribute funding towards a crowdfunding initiative for 11.0 migration.

Is there a rough ballpark/budget in place on the costs required to migrate up to 11.0?

**Comment by lmignon** [comment]
@lukebranch Thank you for your positive feedback. Our estimated budget is described on the initial crowdfunding campaign page https://www.indiegogo.com/projects/alfodoo-for-odoo-11-software#/

Regards

**Comment by lmignon** [comment]
All addons are migrated in https://github.com/acsone/alfodoo/tree/11.0 except cmis_web_proxy and cmis_web_proxy_alf. 
This was made possible thanks to our patrons [erpSOFTapp](https://erpsoftapp.com/) and [LogicaSoft](www.logicasoft.eu).
Thanks to them!
