### ISSUE TITLE
Folder erase in Amlfresco gives an error when accessing through Odoo

### ISSUE THREAD

**Issue by vincentlaurent** [acsone/alfodoo#112]
A user deleted a folder in Alfresco, thus then giving an error in the dociment tab in Odoo (folder not found)

Is there a way to delete the refecrenced node in odoo in order to "reset" the link if the create a new folder ?

Thanks

**Comment by lmignon** [comment]
Hi,

Nothing is provided by the widget to allow a user to delete the reference to the nodreref on the Odoo's model. 
2 possibilities:
* If it's not a common UC you can remove the value into the database.
* If it's a common UC, you can give access to the value (noderef) stored for the CmisFolder field by declaring a related `fields.Char` and displaying it into the view. (You can restrict the access to this new field by specifying a group on the field....). If you remove the value into the related field, the folder is no more referenced by you model instance.

```python
cmis_folder = cmis_fields.CmisFolder()
cmis_folder_noderef =  fields.Char(related='cmis_folder')
```
Regards,

lmi
