### ISSUE TITLE
Owncloud / Nextcloud

### ISSUE THREAD

**Issue by wpichler** [acsone/alfodoo#118]
Hi all,

i am thinking about adding Nextcloud / Owncloud support to alfodoo. Please share your knowledge - is the base code good enough abstracted so that it is possible to add support for Nextcloud/Owncloud ?

**Comment by lmignon** [comment]
H @wpichler 

The base code should work with all storages providing a CMIS1.1 API (Browser binding)

lmi

**Comment by wpichler** [comment]
thats the problem - owncloud does not support cmis. Is more abstraction planned ? For example base modul / extend it with cmis adapter or with owncloud adapter / and cmis adapter could get exctended with alfresco adapter ?

**Comment by lmignon** [comment]
An other approach could be to create a kind of CMIS proxy on top of the  owncloud API.

**Comment by wpichler** [comment]
this would ne an option - but i don't like to add an extra point of failure...

**Comment by lmignon** [comment]
@wpichler Nothing is planned to add more abstraction. You're welcome to propose something.

Regards,

lmi
