### ISSUE TITLE
Drag and drop folders and dowload entire folder

### ISSUE THREAD

**Issue by VedranTe** [acsone/alfodoo#121]
Now users can create a folder and add documents to it.
Wanted functionality is enable users to drag and drop entire folders with all sub-folders and documents.

Users can download documents one by one.
Wanted functionality is to allow the users to download a specific folder or to select files they want to download.

**Comment by lmignon** [comment]
@VedranTe 


> Now users can create a folder and add documents to it.
Wanted functionality is enable users to drag and drop entire folders with all sub-folders and documents.

Indeed that should be a great new functionality. Do you plan to contribute to provide this functionality?

> Users can download documents one by one.
Wanted functionality is to allow the users to download a specific folder or to select files they want to download.

You can already upload several documents at once  (Drag and drop or via the upload dialog)

**Comment by VedranTe** [comment]
@lmignon 
We are interested to contribute financially for this functionality.

**Comment by lmignon** [comment]
@VedranTe Thank you for you proposal.  I don't know if it's technically possible to drag and drop an entire folder with all sub-folders. We must analyze if it's possible and how we can put in place this functionality to evaluate the required effort.

**Comment by lmignon** [comment]
@VedranTe After some research I found a way to implement this functionality at least on webkit based browser (chrome, firefox,  ????) https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry
