### ISSUE TITLE
cmis_folder field not appear correctly on open from many2many field

### ISSUE THREAD

**Issue by ludolelarge** [acsone/alfodoo#125]
When i open many2many something goes wrong

![image](https://user-images.githubusercontent.com/52041088/59854741-c52b9280-9373-11e9-91cd-1cb53b3d8200.png)
![image](https://user-images.githubusercontent.com/52041088/59854754-cc52a080-9373-11e9-9864-85a11640a84b.png)

**Comment by ludolelarge** [comment]
When i open from document_page everything is ok 

![image](https://user-images.githubusercontent.com/52041088/59854855-fc01a880-9373-11e9-97c7-364ae33b02d4.png)

**Comment by lmignon** [comment]
@ludolelarge Thank you for the report. It's a know limitation... When the view is opened into a dialog, the JS is not notified of the view loading and the the databable widget is not initialized....

**Comment by ludolelarge** [comment]
@lmignon thx for return ... Will there be a correction soon ?
