### ISSUE TITLE
Alfresco Content Services 6.1 

### ISSUE THREAD

**Issue by ska-ibees** [acsone/alfodoo#127]
Hi,
Thanks for the fantastic work so far. After following instructions available at http://alfodoo.org/guides/short_guide.html, I was able to integrate alfodoo with Alfresco 5.2.

Just wanted to know if we can use it for  Alfresco Content Services 6.1 in the same way?

Thanks

**Comment by lmignon** [comment]
@go4site Yes it should work (at least that works on my pc)

**Comment by ska-ibees** [comment]
Thanks for the confirmation.
