### ISSUE TITLE
Default Folder for CMIS Field

### ISSUE THREAD

**Issue by cshardey** [acsone/alfodoo#136]
Hello,
Please help me with this configuration. I don't want to create a folder for each mode when I add cmis_field to. I want all users to have the same folder that I specify in the backend. Kindly help.
I tried providing create_parent_get in my field but I keep getting this error  " object has no attribute 'getObjectId' ".

**Comment by lmignon** [comment]
@cshardey You cmis_folder field must be a computed field.
```python
    cmis_folder = fields.CmisFolder(compute="_compute_cmis_folder")
   
    def _compute_cmis_folder(self):
        cmis_folder_field = self._fields['cmis_folder']
        backend = cmis_folder_field.get_backend(self.env)
        folder = backend.get_folder_by_path_parts(
            ["my", "path", "to", "my_folder"], create_if_not_found=True)
        value = folder.getObjectId()
        for record in self:
            record.cmis_folder= value
```
