### ISSUE TITLE
i Got Error while installing alfodoo in odoo 9

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#14]
first of all i installed cmislib (cmislib-0.5.1.tar.gz)  from **https://pypi.python.org/pypi/cmislib/0.5.1**
this are followed by odoo forum instruction(**https://www.odoo.com/forum/help-1/question/cant-install-and-use-odoo-cmis-connector-88414**) after that i copy paste all the file into addons folder but i still i got error like this.
   **from cmislib.browser.binding import safe_urlencode
ImportError: No module named cmislib.browser.binding**

please help me struggling last 2 days give me instruction how to install afodoo for odoo 9

**Comment by lmignon** [comment]
@LakshminarayananOKN 
You've installed the wrong version of cmislib . The one to use is not yet released but can be installed from the sources. You can take a look to the offical documentation to know how to install alfodoo. http://alfodoo.org/guides/install.html

Regards,

lmi

**Comment by bodedra** [comment]
I have faced same issue and resolved it with following command. I am working with Ubuntu OS.

    sudo pip install cmislib
