### ISSUE TITLE
OpenKM result Path with sanitize

### ISSUE THREAD

**Issue by man4tech** [acsone/alfodoo#140]
Hi, we're trying to implement cmis_field module using OpenKM, when click CREATE FOLDER IN DMS, it show a Error concerning Path. 

OpenKM paths starts with  /okm:root/... i check the code and is replacing \/:*?"<>| characters. So the OpenKM path result invalid, we have tried to remove semicolon (:) from the list but itsnt work.

I made a test if i store directly in Odoo DB the uuid generated in OpenKM, i works fine.

How this can be workarounded

**Comment by lmignon** [comment]
Do you have tried to disable the sanitizing method?
```

class CmisBackend(models.Model):

    _inherit = 'cmis.backend'

    def sanitize_cmis_name(self, value, replace_char=None):
        return value
```

I don't know OpenKM and so I've never done a test with this DMS. I would be interested to know if in the end, it could work.
