### ISSUE TITLE
issue with directory

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#16]
Initial directory for writing :.........????...........
local directory or alfresco directory path,

**Comment by lmignon** [comment]
@LakshminarayananOKN The directory into alfresco in which the folder will be created. For exemple: open  the share UI, create an directrory named 'odoo' at root of the repository and put 'odoo/' as initial directory for writing?

**Comment by LakshminarayananOKN** [comment]
no, i just put /
