### ISSUE TITLE
I do't Know how to install and configure in odoo 9

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#18]
first of all i am new for odoo 9 , do't know how to install and which package can i put inside into addons
please help me from basic point to end point.

thanks By
Lakshmianarayanan

**Comment by JosDeGraeve** [comment]
Hi,

There's a lot of ground to cover for your question.

You might want to consider buying the [odoo essentials book](https://essentials.odoo.com/), and/or getting help from an odoo partner.

Regards,

**Comment by LakshminarayananOKN** [comment]
hi,
i have enough knowledge about odoo about technically and functionally. don't know  procedure to install alfodoo-9.0 and connector-cmis-9.0 is enough to install except alfresco

**Comment by lmignon** [comment]
@LakshminarayananOKN Do you have succeeded to install Odoo?

**Comment by LakshminarayananOKN** [comment]
yes
