### ISSUE TITLE
i want know which cmis module suiable for alfodoo odoo 10 module

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#38]
now i need to install alfodoo for odoo version 10, i want to know which cmis module suitable for alfodoo10

**Comment by lmignon** [comment]
@LakshminarayananOKN https://github.com/OCA/connector-cmis The PR https://github.com/OCA/connector-cmis/pull/18 is now merged into https://github.com/OCA/connector-cmis/tree/10.0 Therefore the **cmis** addon is now available for 10.0 (cmis_read and cmis_write are unported)
