### ISSUE TITLE
Downgrade to Odoo 8.0 ?

### ISSUE THREAD

**Issue by ezerouali** [acsone/alfodoo#47]
I manage to downgrade most of the XML and Python.
Now, the modules installs ok in Odoo 8.0, but the Javascript files aren't working.
i.e.: `"odoo.define('cmis_web.form_widgets', function(require) {..."`
generates the following error: "Can't find variable: odoo"
If I replace odoo by openerp, I still get an error: "openerp.define is not a function. (In 'openerp.define', ..."
Has anyone tried to have this working for Odoo 8.0?

**Comment by lmignon** [comment]
@makwin The js APi is different between Odoo9 and openerp8. Even if the downgrade is possible, it requires a good knowledge of the JS api in both versions.

**Comment by lmignon** [comment]
@makwin  I close this issue since it's no more relevant and we don't plan to downgrade alfodoo for Odoo 8.
