### ISSUE TITLE
Alfodoo in Safari browser

### ISSUE THREAD

**Issue by jeanpaulrobineau** [acsone/alfodoo#48]
Hello,

I have a problem with your module in a safari browser. 
The issue is on Ipad, Iphone and Mac OSX in a safari browser.
The dialog box for login is not given, and you get an error that you are not logged in.

Kind Regards,
Jean-Paul Robineau

**Comment by lmignon** [comment]
@jeanpaulrobineau 
Thank you for the report. Nevertheless I don't have safari on my ubuntu machine. It's therefore not possible to me to fix this issue. You must be sure that safari allows cross domain request from JS (CORS ). You should also check that all the headers into the cross domain request are allowed by your configuration of your alfresco server (http://alfodoo.org/guides/install.html#enable-cors-in-alfresco-5-x).

Regards, 

lmi

**Comment by JosDeGraeve** [comment]
Hi,

I have been investigating on this issue.

Both chrome and safari are sending the same origin header, the only difference between both is how they react to the 

What happens with chrome:
1. an ajax request is sent without an authorization header to alfresco
2. alfresco returns status 401 with a json error message payload
3. Chrome displays a popup to the user, requesting for the password
4. an ajax request is sent again with the proper authorization header to alfresco
5. alfresco returns the requested json payload.
6. success

What happens with safari:
1. an ajax request is sent without an authorization header to alfresco
2. alfresco returns status 401 with a json error message payload
3. a second ajax request is sent without an authorization header to alfresco
4. alfresco returns status 401 with a json error message payload
5. Safari displays the error message from the json error payload "...Authentication failed...", but does not prompt the user for a password.
6. failure

I have not been able to figure out why safari does things differently in step 3.
I can't figure out if this is an issue with the cmis.js or superagent.js javascript lib.

any ideas ?

**Comment by kgoderis** [comment]
@lmignon ping....

**Comment by kgoderis** [comment]
@lmignon FYI, on iOS neither Safari, Firefox or Chrome is working, but resulting in an authentication failure.

**Comment by lmignon** [comment]
@kgoderis I'll try to find a MAC to investigate what's wrong on IOS.

**Comment by kgoderis** [comment]
@lmignon Ping.

**Comment by dreispt** [comment]
@lmignon FYI Safari is also available on Windows.
