### ISSUE TITLE
CmisException: Error Could not parse server response at http://127.0.0.1:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#61]
i have installed alfresco in my local system and configured in web.xml cors settings, and then while configuration od cmis back end, got **CmisException: Error Could not parse server response at http://127.0.0.1:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser** this error, can know that is my fault

![screenshot from 2017-07-18 10-58-14](https://user-images.githubusercontent.com/18413399/28302023-70ddca94-6ba8-11e7-9d9d-6476232f56e6.png)
![screenshot from 2017-07-18 10-58-20](https://user-images.githubusercontent.com/18413399/28302024-70e04f8a-6ba8-11e7-9d6d-9737ca6be8bf.png)

**Comment by lmignon** [comment]
@LakshminarayananOKN You should use wireshard to analyse the call and reponse from odoo to alfresco or add a break where the error occurs to see the content in the response from alfreso.

**Comment by lmignon** [comment]
@LakshminarayananOKN  I close this issue. Feel free to reopen-it if it's not fixed.
