### ISSUE TITLE
Unable to find the server at alfrescodemo.eu

### ISSUE THREAD

**Issue by sumankhk** [acsone/alfodoo#67]
@lmignon  I am trying to integrate Alfresco in Odoo for a complete document management solution..I tried to fill the fields with the information u sahred above and i've been getting this error..it says "Unable to find the server at alfrescodemo.eu".....plz let me know what should i do

**Comment by lmignon** [comment]
@sumankhk You must have a complete access to an alfresco server. (alfrescodemo.eu doesn't exist) 

Your alfresco server must be configured to allow http CORS requests. (http://alfodoo.org/guides/install.html)
If you are behind a reverse proxy you must also adapt the alfresco configuration as explained here https://github.com/acsone/alfodoo/pull/20/files#diff-bbb3aae06dfb8e61a58704fd53ab826eR84
If you use https you must adapt the python code as described here.
https://github.com/acsone/alfodoo/issues/15#issuecomment-264881343

Regards

**Comment by sumankhk** [comment]
I am completely new to odoo and alfresco as well...i figured out the earlier problem but now i have anew one...when i open the documents tab i don't get the buttons related to alfresco.Plz help @lmignon

**Comment by sumankhk** [comment]
![gitshot](https://user-images.githubusercontent.com/23263034/30105472-3f60d274-92e8-11e7-86f3-55e18b35148e.png)

**Comment by sumankhk** [comment]
`from odoo import models,fields,api








class advisory(models.Model):
    _name = "advisory"

    document_name = fields.Char(required=True,string="Document name")
    version = fields.Integer(required=True,string="version")
    timestamp = fields.Datetime(required=True,string="Uploaded on:")
`

**Comment by sumankhk** [comment]
`from odoo import models
from ...cmis_field import fields



class DMS(models.Model):
    _inherit = "advisory"
    cmis_folder = fields.CmisFolder()`

**Comment by sumankhk** [comment]
`<record id="main_form_view" model="ir.ui.view">
        <field name="name">dms form</field>
        <field name="model">advisory</field>
        
        <field name="arch" type="xml">
        <form>
            
            <sheet>
                    <group name="group-top">

                        <group name="group-left">
                            <field name="document_name"/>
                            <field name="version"/>

                        </group>
                        <group name="group-right">
                            <field name="timestamp"/>
                            

                        </group>
                        <notebook position="inside">
                           <page string="Documents" groups="base.group_user">
                            <field name="cmis_folder"/>
                           </page>
                        </notebook>

                    </group>
                    
            </sheet>
        </form>
        </field> 
    </record> `

**Comment by sumankhk** [comment]
@lmignon  What am i missing?plz help

**Comment by sumankhk** [comment]
@zakiuu  @sbidoul @Cedric-Pigeon @Olivier-LAURENT @lmignon .....i need help people...and its kinda urgent
