### ISSUE TITLE
Unable to Preview .docx and .doc when uploaded from alfodoo

### ISSUE THREAD

**Issue by Bank-Afolabi** [acsone/alfodoo#68]
Hi,
  I can't preview .docx and .doc files when i upload the files from alfodoo  other file types (image,xlsx,pdf) works fine but uploading through alfresco share i can preview the files(docx,docs)  on alfodoo. 

I am working on Ubuntu 16.04 running odoo version 10.0 and as well Alfresco Community v5.2.0

 I noticed the HTTP request to alfresco api is different for docx and pdf  when viewing from alfodoo .
 **PDF**
 "GET **/alfresco/api/-default-/public/cmis/versions/1.1/browser/root**?succinct=true&cmisselector=content&objectId

 **docx /doc**
GET **/alfresco/api/node/workspace/SpacesStore/**4d6c1e11-6e1c-489e-99ee-0206161f8da7/content/thumbnails/pdf/Training%20.docx?c=force&lastModified=pdf%936

Any help to resolve this ?

**Comment by Bank-Afolabi** [comment]
Any help ?

**Comment by lmignon** [comment]
@Bank-Afolabi The url to the alfresco api seems to be wrong. It should look like
`http://x.y.z/alfresco/s/api`
![image](https://user-images.githubusercontent.com/544090/30377074-bf8fd2b4-988e-11e7-9744-c6a75c509be7.png)

**Comment by Bank-Afolabi** [comment]
@lmignon 
Thanks for responding 
 http://x.y.z /alfresco/s/api   for  Alfresco Community v5.2.0 gives 404 not found http response.
only   http://x.y.z /alfresco/api is valid  and thats what am using , my only issue is on docx it calls a different api anytime i upload the file from alfodoo directly.

**Comment by lmignon** [comment]
@Bank-Afolabi For the preview, alfodoo check in the available renditions returned for a document by cmis if one exists for 'pdf'. If a rendition exists for pdf alfodoo calls the CMIS content service ("/alfresco/api/-default-/public/cmis/versions/1.1/browser/root?succinct=true&cmisselector=content&objectId")
If no rendition is found, alfodoo try to call the alfresco api to force the transformation of your docx into pdf... (**/alfresco/api/node/workspace/SpacesStore/**4d6c1e11-6e1c-489e-99ee-0206161f8da7/content/thumbnails/pdf/Training%20.docx?c=force&lastModified=pdf%936)

This url is maybe not valid with alfresco community V5.2.0. It works with alfresco-201701, alfresco-201605, ....

**Comment by Bank-Afolabi** [comment]
@lmignon  Ok Please , how do i  resolve this , from my alfresco share? or how can I make alfodoo find docx rendition instead of converting to pdf.

**Putting in mind that when I  upload directly the docx file from alfresco share , alfodoo does not have issue rendering it**. 
  Thanks

**Comment by lmignon** [comment]
@Bank-Afolabi 

> Putting in mind that when I upload directly the docx file from alfresco share , alfodoo does not have issue rendering it.

It's because once the document has been rendered into pdf by alfresco, it's available into the renditions information received from the CMIS service.

To solve this issue we must know which alfresco service can be called to transform a document from docx to pdf using the alfresco api and modify the code here https://github.com/acsone/alfodoo/blob/10.0/cmis_web_alf/static/src/js/form_widgets.js#L33 to build the right url

**Comment by Bank-Afolabi** [comment]
@lmignon Thanks for the details.
  I hope you and your team will find the time to do this.  

Nice work.

**Comment by lmignon** [comment]
@Bank-Afolabi you're welcome to sponsor this work... :smirk:

**Comment by Bank-Afolabi** [comment]
Ok ..will check your store at the conference in Belgium.
