### ISSUE TITLE
cmis.backend error

### ISSUE THREAD

**Issue by sumankhk** [acsone/alfodoo#75]
![error](https://user-images.githubusercontent.com/23263034/31481741-7322dfce-af14-11e7-99f6-391b41397c94.png)
![cmisconf](https://user-images.githubusercontent.com/23263034/31481797-c6360902-af14-11e7-9b1f-a0a626c40836.png)

Why am i getting this error?How do i resolve it? Urgent help needed.

**Comment by lmignon** [comment]
@sumankhk do you have 'cmis_field' into the depends list of your custom addon?

**Comment by sumankhk** [comment]
Thanks for your comment @lmignon 
.It resolved that issue.Now the problem is when i click the "Create Folder in DMS "button it gives me key error.This is the same error i get when testing directory during Cmis backend configuration.I have got a deadline tommorow and i need to complete this.

![keyerror](https://user-images.githubusercontent.com/23263034/31483878-b17fe1fa-af1d-11e7-997f-444119a21acb.png)

**Comment by lmignon** [comment]
@sumankhk You have a blank char at the beginning of your location url ' https'. Moreover your share url should be the root of alfresco sharei IOW https://localhost:8080/share

**Comment by sumankhk** [comment]
I am now getting a new error SSLHandshakeError.can u help me with this ? @lmignon 
![ssl error](https://user-images.githubusercontent.com/23263034/31485759-761943d4-af24-11e7-8fef-58c0d57e4bbf.png)

**Comment by lmignon** [comment]
@sumankhk Sorry I can't debug for you. In such a case google is your friend. The problem is not related to the module. IMO if you don't use https it should work. Takes a look also here https://github.com/acsone/alfodoo/issues/15#issuecomment-264881343

**Comment by sumankhk** [comment]
@lmignon Thanks for your help man.It was really nice of you to help and i do realize i was asking way too much.Thanks anyways.

**Comment by lmignon** [comment]
@sumankhk You are welcome. Feel free to contribute. By curiosity in which context to you plan to use these addons?

lmi

**Comment by sumankhk** [comment]
I am supposed to integrate alfresco in a system for project for document management.

**Comment by sumankhk** [comment]
I tried to solve earlier problem and now i have a new error.Can anybody help me with this?
![sslerror](https://user-images.githubusercontent.com/23263034/31491681-a03dffca-af37-11e7-8e03-e164e8f0dd61.png) @lmignon

**Comment by lmignon** [comment]
@sumankhk Are you sure that alfresco is available over httpS on  localhost???
