### ISSUE TITLE
download/preview/goto alfresco should work on last version by default

### ISSUE THREAD

**Issue by sbidoul** [acsone/alfodoo#83]
Here is the problematic scenario:

- view a document folder in Odoo
- goto to alfresco
- modify the document
- refresh the preview in alfresco
- come back to Odoo
- download the document => we get the previous version, this is unexpected
- preview the document => ok (to be verified)
- go to alfresco with the flower icon => a pdf preview error occurs (might not be related?)

**Comment by rousseldenis** [comment]
I've just tested the PR #84

I confirm that the preview is updated.

But the download will get the last document version on second click not the first

@lmignon 

UPD : The flower link works

**Comment by rousseldenis** [comment]
@lmignon @sbidoul Last commit works for me!

**Comment by lmignon** [comment]
Fixed in https://github.com/acsone/alfodoo/pull/84
