### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by sumankhk** [acsone/alfodoo#86]
In the alfodoo developer's guide ,the SSL issue has been identifed.But i m not quite aure about where to use that code .Could any body help me out?
![alfodo](https://user-images.githubusercontent.com/23263034/32268124-d0db653a-bf15-11e7-805f-7fc1c3b90864.png)

What exactly does custom odoo addon mean?

**Comment by lmignon** [comment]
> What exactly does custom odoo addon mean?

An addon you develop to extend the Odoo for your specific needs.

**Comment by sumankhk** [comment]
The buttons related to alfresco don't appear after i click on "Create folder in DMS" button....yet no error message is shown.I can't figure out the problem..Could you help me out?
@lmignon

**Comment by lmignon** [comment]
@sumankhk  You should look for error messages into the browser console.  Your alfresco should also be properly configured to allow CORS requests. http://alfodoo.org/guides/install.html

**Comment by sumankhk** [comment]
![jserror](https://user-images.githubusercontent.com/23263034/32819123-97d36df2-c9ef-11e7-8510-55cb42199d1e.png)
This is the error i'm getting....could you help?
@lmignon @pkhazzaka
