### ISSUE TITLE
TypeError: this.gen_cmis_session_token is not a function

### ISSUE THREAD

**Issue by wpichler** [acsone/alfodoo#94]
I've installed from branch 10.0 - with current odoo community 10.0.
Alfresco running behind proxy - backend directory test does work. I've added cmis folder to res.partner - this does work - i can see the widget - i can upload files - but then it do get the above error.

![bildschirmfoto von 2018-01-12 17-50-35](https://user-images.githubusercontent.com/13257734/34885703-23ff32d0-f7c1-11e7-8c96-386e5173f729.png)

**Comment by wpichler** [comment]
ah - my fault - i did forgot to remove the proxy module ;-)

**Comment by phuhk** [comment]
hi mate, I have same problem when turn on Debug mode with assets. What are you mean remove proxy module mean? Uninstall both cmis_web_proxy and cmis_web_proxu_alf, right? Any doucment about it?
