### ISSUE TITLE
Unable to Configuration in cmis

### ISSUE THREAD

**Issue by akhodifad** [acsone/alfodoo#95]
I have occurred this error,

![ibcgeddflgniifpf](https://user-images.githubusercontent.com/32675315/34946856-733f73f4-fa2e-11e7-9429-f8dbe8070ed0.png)

**Comment by lmignon** [comment]
@akhodifad Can you show me a screenshot of your backend configuration form PLZ. With only a stacktrace it's not possible to figure out what's happen.

**Comment by akhodifad** [comment]
I click to test directory button.  
![clicktesting](https://user-images.githubusercontent.com/32675315/34983202-c5cb9112-fad2-11e7-8f2a-c84b35dd7cbd.png)
then give me this error
![error](https://user-images.githubusercontent.com/32675315/34983351-38c21470-fad3-11e7-8800-b39bd4cda597.png)

**Comment by lmignon** [comment]
@akhodifad As specified into the documentation, the field `location`must hold the url of the browser binding endpoint of your alfresco server (http://alfodoo.org/guides/short_guide.html#configure-the-cmis-connector) n your case: http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser/
