### ISSUE TITLE
Cannot configure Alfodoo

### ISSUE THREAD

**Issue by asoral** [acsone/alfodoo#96]
My Alfresco is working fine as a standalone application. When I add the following code in the web.xml file under alfresco/tomcat/conf/web.xml, I cannot even run Alfresco -

```
<!-- CORS Filter Begin -->
<filter>
    <filter-name>CORS</filter-name>
    <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
    <init-param>
      <param-name>cors.allowed.origins</param-name>
      <param-value>http://localhost:8069,https://127:0.0.1:8080</param-value>
    </init-param>
    <init-param>
      <param-name>cors.allowed.methods</param-name>
      <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
    </init-param>
    <init-param>
      <param-name>cors.allowed.headers</param-name>
      <param-value>origin, authorization, x-file-size, x-file-name, content-type, accept, x-file-type, DNT, x-customheader ,keep-alive ,user-agent ,x-requested-with ,if-modified-since, cache-control,accept-ranges,content-encoding,content-length</param-value>
    </init-param>
    <init-param>
      <param-name>cors.exposed.headers</param-name>
      <param-value>origin, authorization, x-file-size, x-file-name, content-type, accept, x-file-type, DNT, x-customheader ,keep-alive ,user-agent ,x-requested-with ,if-modified-since, cache-control,accept-ranges,content-encoding,content-length</param-value>
    </init-param>
    <init-param>
      <param-name>cors.support.credentials</param-name>
      <param-value>true</param-value>
    </init-param>
    <init-param>
      <param-name>cors.preflight.maxage</param-name>
      <param-value>3600</param-value>
    </init-param>
 </filter>
 <!-- CORS Filter End -->

 <!-- CORS Filter Mappings Begin -->
 <filter-mapping>
    <filter-name>CORS</filter-name>
    <url-pattern>/api/*</url-pattern>
    <url-pattern>/service/*</url-pattern>
    <url-pattern>/s/*</url-pattern>
    <url-pattern>/cmisbrowser/*</url-pattern>
 </filter-mapping>
```

So, then when I try to connect my Odoo with Alfresco, system gives the below error -

![image](https://user-images.githubusercontent.com/11851156/34978828-8337bafe-fac5-11e7-872a-b066d4efed75.png)

**Comment by lmignon** [comment]
@asoral You describe 2 errors. The first one is related to the way you must configure alfresco to enable CORS requests. The other one is related to how you must configure your cmis backend into Odoo. 
For the first one, what's the url of your alfresco server: Into 'cors.allowed.origins' you must put at least 2 urls. The one of your odoo server and the one of your alfresco server.
ex:
 odoo: http://localhost:8069
 alfresco http://myalfresco.com
cors.allowed.origins 'http://localhost:8069, http://myalfresco.com'

If you are not sure you can set the value '*' for 'cors.allowed.origins' to allow access from everywhere (not recommended at all).

**Comment by lmignon** [comment]
@asoral I close this issue. Feel free to reopen-it if it's not fixed.
